<?php

function commerce_payeer_settings_form($settings = NULL)
{
	$form = array();

	$settings = (array) $settings + array(
		'merchant_url' => '',
		'merchant_id' => '',
		'secret_key' => '',
		'currency' => '',
		'order_desc' => '',
		'ip_filter' => '',
		'email_error' => '',
		'payeer_log' => array('1'),
		'success_message' => '',
		'fail_message' => '',
	);

	$form['merchant_url'] = array(
		'#type' => 'textfield',
		'#title' => t('URL мерчанта'),
		'#description' => t(' ссылка для оплаты в системе Payeer'),
		'#default_value' => '//payeer.com/merchant/',
	);

	$form['merchant_id'] = array(
		'#type' => 'textfield',
		'#title' => t('Идентификатор магазина'),
		'#description' => t(' Идентификатор магазина, зарегистрированного в системе "PAYEER".<br/>Узнать его можно в <a href="http://www.payeer.com/account/">аккаунте Payeer</a>: "Аккаунт -> Мой магазин -> Изменить".'),
		'#default_value' => $settings['merchant_id'],
	);

	$form['secret_key'] = array(
		'#type' => 'textfield',
		'#title' => t('Секретный ключ'),
		'#description' => t(' Секретный ключ оповещения о выполнении платежа,<br/>который используется для проверки целостности полученной информации<br/>и однозначной идентификации отправителя.<br/>Должен совпадать с секретным ключем, указанным в <a href="http://www.payeer.com/account/">аккаунте Payeer</a>: "Аккаунт -> Мой магазин -> Изменить".'),
		'#default_value' => $settings['secret_key'],
	);

	$form['order_desc'] = array(
		'#type' => 'textfield',
		'#title' => t('Комментарий к заказу'),
		'#description' => t(' Описание к оплате заказов'),
		'#default_value' => $settings['order_desc'],
	);

	$form['ip_filter'] = array(
		'#type' => 'textfield',
		'#title' => t('IP - фильтр'),
		'#description' => t(' Список доверенных ip адресов, можно указать маску'),
		'#default_value' => $settings['ip_filter'],
	);

	$form['email_error'] = array(
		'#type' => 'textfield',
		'#title' => t('Email'),
		'#description' => t(' Email для отправки ошибок оплаты'),
		'#default_value' => $settings['email_error'],
	);
	
	$form['payeer_log'] = array(
		'#type' => 'textfield',
		'#title' => t('Путь до файла для журнала оплат через Payeer (например, /payeer_orders.log)'),
		'#description' => t(' Если путь не указан, то журнал не записывается'),
		'#default_value' => $settings['payeer_log'],
	);

	$form['success_message'] = array(
		'#type' => 'textarea',
		'#rows' => 3,
		'#title' => t('Удачный платеж'),
		'#description' => t('Сообщение об удачной оплате'),
		'#default_value' => $settings['success_message'],
	);

	$form['fail_message'] = array(
		'#type' => 'textarea',
		'#rows' => 3,
		'#title' => t('Неудачный платеж'),
		'#description' => t('Сообщение о неудачной оплате'),
		'#default_value' => $settings['fail_message'],
	);

	$form['url'] = array(
		'#type' => 'fieldset',
		'#collapsible' => TRUE,
		'#title' => t('URL (success, fail, status) для магазина Payeer')
	);

	$form['url']['success'] = array(
		'#type'          => 'textfield',
		'#title'         => t('URL успешной оплаты'),
		'#value' => url('payeer/success', array('absolute' => TRUE)),
		'#description'   => t("укажите этот url в аккаунте Payeer")
	);

	$form['url']['fail'] = array(
		'#type'          => 'textfield',
		'#title'         => t('URL неуспешной оплаты'),
		'#value' => url('payeer/fail', array('absolute' => TRUE)),
		'#description'   => t("укажите этот url в аккаунте Payeer")
	);
	
	$form['url']['status'] = array(
		'#type'          => 'textfield',
		'#title'         => t('URL обработчика'),
		'#value' => url('payeer/status', array('absolute' => TRUE)),
		'#description'   => t("укажите этот url в аккаунте Payeer")
	);

	$form['#submit'][] = variable_set('commerce_payeer_settings', $form);

	return $form;
}

function commerce_payeer_commerce_payment_method_info() 
{
	$payment_methods = array();
	
	$payment_methods['commerce_payeer'] = array(
		'base' => 'commerce_payeer',
		'title' => t('Payeer'),
		'short_title' => t('Payeer'),
		'display_title' => t('Payeer'),
		'description' => t('Integrates Payeer Merchant'),
		'terminal' => FALSE,
		'offsite' => TRUE,
		'active' => TRUE,
	);

	return $payment_methods;
}

function commerce_payeer_submit_form($payment_method, $pane_values, $checkout_pane, $order) 
{
	$build = array();
	$text = theme('image', array(
		'path' => 'http://payeer.com/bitrix/templates/difiz/images/logo.png',
		'alt' => t('Payeer'),
		'title' => t('Payeer'),
		'attributes' => array('class' => 'logo-payeer'),
	));
	$text .= '<div class="desc">' . t('Payeer - Используйте множество платежных систем и банков в одном кошельке!') . '</div>';
	$build['print_receipt'] = array('#markup' => $text);
	return $build;
}

function commerce_payeer_menu() 
{
	$items['payeer/status'] = array(
		'title' => 'Cтатус оплаты заказа',
		'page callback' => 'commerce_payeer_status',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
	$items['payeer/success'] = array(
		'title' => 'Успешный платеж',
		'page callback' => 'commerce_payeer_success',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	
	$items['payeer/fail'] = array(
		'title' => 'Неудачный платеж',
		'page callback' => 'commerce_payeer_fail',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	
	return $items;
}

function commerce_payeer_redirect_form($form, &$form_state, $order, $payment_method)
{
	return commerce_payeer_build_redirect_form($form, $form_state, $order, $payment_method['settings']);
}

function commerce_payeer_build_redirect_form($form, &$form_state, $order, $settings) 
{
	$wrapper = entity_metadata_wrapper('commerce_order', $order);
	
	$m_url = commerce_payeer_get_settings('merchant_url');
	
	$m_shop = commerce_payeer_get_settings('merchant_id');
	
	$m_orderid = $order->order_id;
	
	$m_curr = $wrapper->commerce_order_total->currency_code->value();
	
	$amount = $wrapper->commerce_order_total->amount->value();
	
	$m_amount = commerce_currency_amount_to_decimal($amount, $m_curr);
	
	$m_desc = base64_encode(commerce_payeer_get_settings('order_desc'));

	if ($m_curr == 'RUR')
	{
		$m_curr = 'RUB';
	}

	$m_key = commerce_payeer_get_settings('secret_key');

	$arHash = array(
		$m_shop,
		$m_orderid,
		$m_amount,
		$m_curr,
		$m_desc,
		$m_key
	);
	
	$sign = strtoupper(hash('sha256', implode(':', $arHash)));

	$form['#action'] = $m_url;
	
	$form['m_shop'] = array(
		'#type' => 'hidden',
		'#value' => $m_shop,
	);
	
	$form['m_orderid'] = array(
		'#type' => 'hidden',
		'#value' => $m_orderid,
	);

	$form['m_amount'] = array(
		'#type' => 'hidden',
		'#value' => $m_amount,
	);
	
	$form['m_curr'] = array(
		'#type' => 'hidden',
		'#value' => $m_curr,
	);
	
	$form['m_desc'] = array(
		'#type' => 'hidden',
		'#value' => $m_desc,
	);
	
	$form['m_sign'] = array(
		'#type' => 'hidden',
		'#value' => $sign,
	);
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Оплатить'),
	);
	
	return $form;
}

function commerce_payeer_form_commerce_checkout_form_payment_alter(&$form, &$form_state, $form_id)
{
	unset($form["#form_id"]);
	unset($form["form_id"]);
	unset($form["form_token"]);
	unset($form["form_build_id"]);
}

function commerce_payeer_get_settings($settings) 
{
	$output = '';
	$vars = variable_get('commerce_payeer_settings', '');
	
	if (!empty($vars)) 
	{
		foreach ($vars as $key=>$var) 
		{
			if ($key == $settings) 
			{
				$output = $vars[$key]['#default_value'];
				break;
			}
		}
	}
	
	return $output;
}

function commerce_payeer_success() 
{
	$build = array();
	
	if (isset($_GET['m_orderid']) && isset($_GET['m_status'])) 
	{
		$message = t('Спасибо, ваш заказ оплачен! Ордер #@shop_order,<br />', array('@shop_order' => $_GET['m_orderid']));
		
		drupal_set_message($message, 'status');
		
		if ($message = commerce_payeer_get_settings('success_message')) 
		{
			$build['message_success']['#markup'] = $message;
		}
	}
	else
	{
		$build = MENU_ACCESS_DENIED;
	}
	
	return $build;
}

function commerce_payeer_fail() 
{
	drupal_set_message(t('Payment unsuccessful!'), 'error');
	
	$build = array();
	
	if ($message = commerce_payeer_get_settings('fail_message')) 
	{
		$build['message_fail']['#markup'] = $message;
	}
	
	return $build;
}

function commerce_payeer_status() 
{
	if (!empty($_POST))
	{
		if (isset($_POST['m_operation_id']) && isset($_POST['m_sign']))
		{
			$m_key = commerce_payeer_get_settings('secret_key');
			
			$payeer_log = commerce_payeer_get_settings('payeer_log');
			
			$arHash = array(
				$_POST['m_operation_id'],
				$_POST['m_operation_ps'],
				$_POST['m_operation_date'],
				$_POST['m_operation_pay_date'],
				$_POST['m_shop'],
				$_POST['m_orderid'],
				$_POST['m_amount'],
				$_POST['m_curr'],
				$_POST['m_desc'],
				$_POST['m_status'],
				$m_key
			);
					
			$sign_hash = strtoupper(hash('sha256', implode(':', $arHash)));
			
			$log_text = 
				"--------------------------------------------------------\n".
				"operation id		" . $_POST["m_operation_id"] . "\n".
				"operation ps		" . $_POST["m_operation_ps"] . "\n".
				"operation date		" . $_POST["m_operation_date"] . "\n".
				"operation pay date	" . $_POST["m_operation_pay_date"] . "\n".
				"shop				" . $_POST["m_shop"] . "\n".
				"order id			" . $_POST["m_orderid"] . "\n".
				"amount				" . $_POST["m_amount"] . "\n".
				"currency			" . $_POST["m_curr"] . "\n".
				"description		" . base64_decode($_POST["m_desc"]) . "\n".
				"status				" . $_POST["m_status"] . "\n".
				"sign				" . $_POST["m_sign"] . "\n\n";
			
			if (!empty($payeer_log))
			{	
				file_put_contents($_SERVER['DOCUMENT_ROOT'] . $payeer_log, $log_text, FILE_APPEND);
			}
			
			// проверка принадлежности ip списку доверенных ip
	
			$ip_filter = commerce_payeer_get_settings('ip_filter');
			
			$list_ip_str = str_replace(' ', '', $ip_filter);
			
			if (!empty($list_ip_str)) 
			{
				$list_ip = explode(',', $list_ip_str);
				$this_ip = $_SERVER['REMOTE_ADDR'];
				$this_ip_field = explode('.', $this_ip);
				$list_ip_field = array();
				$i = 0;
				$valid_ip = FALSE;
				foreach ($list_ip as $ip)
				{
					$ip_field[$i] = explode('.', $ip);
					if ((($this_ip_field[0] ==  $ip_field[$i][0]) or ($ip_field[$i][0] == '*')) and
						(($this_ip_field[1] ==  $ip_field[$i][1]) or ($ip_field[$i][1] == '*')) and
						(($this_ip_field[2] ==  $ip_field[$i][2]) or ($ip_field[$i][2] == '*')) and
						(($this_ip_field[3] ==  $ip_field[$i][3]) or ($ip_field[$i][3] == '*')))
						{
							$valid_ip = TRUE;
							break;
						}
					$i++;
				}
			}
			else
			{
				$valid_ip = TRUE;
			}
	
			if ($_POST['m_sign'] == $sign_hash && $_POST['m_status'] == 'success' && $valid_ip)
			{
				commerce_payeer_create_transaction($_POST['m_orderid'], abs($_POST['m_amount']), $_POST['m_operation_id']);
				
				exit ($_POST['m_orderid'] . '|success');
			}
			else
			{
				$email_error = commerce_payeer_get_settings('email_error');
				
				$to = $email_error;
				$subject = "Ошибка оплаты";
				$message = "Не удалось провести платёж через систему Payeer по следующим причинам:\n\n";
				
				if ($_POST["m_sign"] != $sign_hash)
				{
					$message .= " - Не совпадают цифровые подписи\n";
				}
				
				if ($_POST['m_status'] != "success")
				{
					$message .= " - Cтатус платежа не является success\n";
				}
				
				if (!$valid_ip)
				{
					$message .= " - ip-адрес сервера не является доверенным\n";
					$message .= "   доверенные ip: " . $ip_filter . "\n";
					$message .= "   ip текущего сервера: " . $_SERVER['REMOTE_ADDR'] . "\n";
				}
				
				$message .= "\n" . $log_text;
				$headers = "From: no-reply@" . $_SERVER['HTTP_SERVER']."\r\nContent-type: text/plain; charset=utf-8 \r\n";
				mail($to, $subject, $message, $headers);
				
				exit ($_POST['m_orderid'] . '|error');
			}
		}
	}
}

function commerce_payeer_create_transaction($order_id, $amount, $trans_id) 
{
	$order = commerce_order_load($order_id);
	
	$payment_method = commerce_payment_method_instance_load($order->data['payment_method']);

	$wrapper = entity_metadata_wrapper('commerce_order', $order);

	$currency_code = $wrapper->commerce_order_total->currency_code->value();

	$transaction = commerce_payment_transaction_new('commerce_payeer', $order->order_id);
	
	$transaction->instance_id = $payment_method['instance_id'];
	
	$transaction->amount = $amount * 100;
	
	$transaction->currency_code = $currency_code;
	
	$transaction->remote_id = $trans_id;

	$transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
	
	$transaction->message = '';
	
	$transaction->message_variables = array();

	commerce_payment_transaction_save($transaction);
	
	rules_invoke_all('commerce_checkout_complete', $order);
}

function commerce_payeer_server_fail_url()
{
	return url('payeer/fail', array('absolute' => TRUE));
}

function this_server_url()
{
	return url('/', array('absolute' => TRUE));
}

